from selenium.webdriver.common.by import By

from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
initial_page = (By.ID, 'to')
button_ask_taxi = (By.CSS_SELECTOR, ".button.round")
button_select_comfort = (By.XPATH, "//div[@class='tcard-title' and text()='Comfort']")
button_select_number = (By.CSS_SELECTOR, ".np-button")
phone_number = (By.CSS_SELECTOR, ".input#phone.input")
code = (By.CSS_SELECTOR, "#code.input")
button_phone_number_next = (By.XPATH, "//button[@type='submit' and @class='button full' and text()='Siguiente']")
confirm_code = (By.XPATH, "//button[@type='submit' and @class='button full' and text()='Confirmar']")
payment_method = (By.CSS_SELECTOR, ".pp-button.filled")
add_payment_method = (By.CSS_SELECTOR, ".pp-plus-container")
credit_card = (By.ID, "number")
code_credit_card = (By.CSS_SELECTOR, "input.card-input#code")
button_add_credit_card = (By.XPATH, "//button[@type='submit' and @class='button full' and text()='Agregar']")
button_exit_add_payment_method = (By.CSS_SELECTOR, "div.payment-picker.open div.modal div.section.active button.close-button.section-close")
button_order_requirement = (By.CSS_SELECTOR, ".reqs-header")
button_ice_cream = (By.CSS_SELECTOR, "div.r-link")
comment = (By.CSS_SELECTOR, "input#comment")
label_comment = (By.XPATH, "//label[@class='label' and @for='comment' and text()='Mensaje para el conductor...']")
label_blanket_and_handkerchief = (By.XPATH, "//div[@class='r-sw-label' and text()='Manta y pañuelos']")
blanket_and_handkerchief = (By.CSS_SELECTOR, "span.slider.round")
label_ice_cream = (By.XPATH, "//div[@class='r-counter-label' and text()='Helado']")

add_ice_cream = (By.CSS_SELECTOR, "div.counter-plus")
button_reserve = (By.CSS_SELECTOR, "button.smart-button")
taxi_confirmation = (By.CSS_SELECTOR, "div.order-btn-group div.order-button")
last_modal = (By.XPATH, "//div[@class='order-header-title' and text()='Buscar automóvil']")
